
language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew tap caskroom/cask
        - brew cask install powershell

script:
  - pwsh -f "./test.ps1"

